name: "Upload SARIF"
# Run workflow each time code is pushed to your repository and on a schedule.

on:
  push:

jobs:
  build:
  runs-on: ubuntu-latest
    steps:
    # This step checks out a copy of your repository.
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif
